### ISSUE TITLE
Images collapsing with no way to expand them again

### ISSUE THREAD

**Issue by chucktheviking** [typefully/minimal-twitter#164] opened 2023-02-08 18:07 UTC
I don't know if this is a recent change, or there is a setting for this, but as of the last 2 days I've noticed posts with images are often having those images collapse. I also cannot find a way to un-collapse the image without reloading the tweet, but that then just results in it collapsing again. Example.
Here is a Tweet with the image collapsed.
![image](https://user-images.githubusercontent.com/22416392/217614810-a6f8c52c-6632-4ebe-89c5-ac8b2047bfdd.png)

After I clicked into the Tweet, the image did load.
![image](https://user-images.githubusercontent.com/22416392/217614903-463115a5-8638-4030-b477-d178f68a68b8.png)

but shortly after it collapsed again.

I first troubleshot by disabling the Minimal Twitter Extension, and the collapsing of images completely stopped. So it's something with Minimal Twitter, or it's interaction with a change Twitter did.

**Comment by chucktheviking** [comment] 2023-02-08 18:22
Here is an example of what it does on multiple image posts.
![msedge_qOoZemz0bv](https://user-images.githubusercontent.com/22416392/217618315-4b845ec9-f2ec-4d65-b92f-61045cac51a5.gif)

**Comment by deadcoder0904** [comment] 2023-02-09 04:20
yeah, i guess the classNames of divs changed & did this effect. started happening since 24 hours ago so very recent change.

**Comment by suyalcinkaya** [comment] 2023-02-09 09:26
Also the counts disappear.

<img width="700" alt="Screen Shot 2023-02-09 at 10 24 30" src="https://user-images.githubusercontent.com/16385367/217771352-8c390b51-8396-4cd5-a181-15308a6756bf.png">

**Comment by thomaswang** [comment] 2023-02-09 11:17
Hey thanks for flagging, fixed here: https://github.com/typefully/minimal-twitter/commit/524467163356454a37bd587a09901b19d4c6ed70

**Comment by thomaswang** [comment] 2023-02-09 11:19
For now to fix in current version, please check turn on / check "Remove View Count from Tweets" and refresh.

**Comment by akoskm** [comment] 2023-02-23 06:46
@thomaswang so this is currently a workaround, right? There's no way to not break the images _and_ have the View Count shown?

**Comment by thomaswang** [comment] 2023-02-23 07:56
@akoskm it's still an issue we're investigating, 5.1.2 did not completely fix the issue

**Comment by akoskm** [comment] 2023-02-23 08:13
@thomaswang sure, let me know if I can help you reproduce this. I tested it in Brave and Safari, and both have the same issue.

**Comment by thomaswang** [comment] 2023-02-25 14:20
Confirmed fixed in `5.1.3`, thanks everyone for the help

**Closed by thomaswang** 2023-02-25 14:20 UTC
